name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build all
      run: make build
    - name: Run Test
      run: make test check clippy fmt
